---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
  labels:
    app: springboot-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
      - name: springboot-hello
        image: naresh240/springboothello:ImageTag
        ports:
        - containerPort: 8080
